# Generated by Django 5.2 on 2026-01-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        ('polizas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('moneda', models.CharField(db_index=True, default='MXN', max_length=3)),
                ('porcentaje', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada')], db_index=True, default='PENDIENTE', max_length=10)),
                ('fecha_pago', models.DateField(blank=True, db_index=True, null=True)),
                ('agente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comisiones', to=settings.AUTH_USER_MODEL)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comisiones', to='polizas.poliza')),
            ],
            options={
                'permissions': [('manage_comisiones', 'Puede administrar comisiones')],
                'indexes': [models.Index(fields=['agente', 'estatus'], name='finanzas_co_agente__f1d475_idx'), models.Index(fields=['poliza', 'estatus'], name='finanzas_co_poliza__54fe3b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('moneda', models.CharField(db_index=True, default='MXN', max_length=3)),
                ('fecha_programada', models.DateField(db_index=True)),
                ('fecha_pago', models.DateField(blank=True, db_index=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('metodo', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('referencia', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('estatus', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], db_index=True, default='PENDIENTE', max_length=10)),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos', to='documentos.documento')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='polizas.poliza')),
            ],
            options={
                'permissions': [('manage_pagos', 'Puede administrar pagos')],
                'indexes': [models.Index(fields=['estatus', 'fecha_programada'], name='finanzas_pa_estatus_57ac4f_idx'), models.Index(fields=['poliza', 'estatus'], name='finanzas_pa_poliza__d4bb5f_idx')],
            },
        ),
    ]
