# Generated by Django 5.2 on 2026-03-20 04:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_alter_cliente_options'),
        ('documentos', '0001_initial'),
        ('finanzas', '0001_initial'),
        ('polizas', '0011_alter_polizaevento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoTransaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('tipo', models.CharField(choices=[('CHECKOUT_CREADO', 'Checkout creado'), ('WEBHOOK_RECIBIDO', 'Webhook recibido'), ('PAYMENT_APPROVED', 'Payment approved'), ('PAYMENT_REJECTED', 'Payment rejected'), ('PAYMENT_PENDING', 'Payment pending'), ('RECONCILIACION_OK', 'Conciliación OK'), ('RECONCILIACION_ERROR', 'Conciliación error')], db_index=True, max_length=40)),
                ('provider_payment_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('provider_preference_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('provider_status', models.CharField(blank=True, max_length=60, null=True)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('moneda', models.CharField(default='MXN', max_length=10)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('procesado', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Transacción de pago',
                'verbose_name_plural': 'Transacciones de pago',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AlterModelOptions(
            name='pago',
            options={'ordering': ['-created_at', '-id'], 'verbose_name': 'Pago', 'verbose_name_plural': 'Pagos'},
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='finanzas_pa_estatus_57ac4f_idx',
        ),
        migrations.RemoveIndex(
            model_name='pago',
            name='finanzas_pa_poliza__d4bb5f_idx',
        ),
        migrations.AddField(
            model_name='pago',
            name='checkout_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='crm.cliente'),
        ),
        migrations.AddField(
            model_name='pago',
            name='comision_provider',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='pago',
            name='concepto',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='pago',
            name='descripcion',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_pago_provider',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='monto_pagado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto efectivamente pagado/conciliado por el provider.', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='pago',
            name='observaciones',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='pago',
            name='payload_resumen_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pago',
            name='provider',
            field=models.CharField(blank=True, choices=[('MERCADOPAGO', 'MercadoPago'), ('STRIPE', 'Stripe')], db_index=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='provider_payment_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del pago devuelto por el provider.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='provider_preference_id',
            field=models.CharField(blank=True, db_index=True, help_text='ID del checkout/preference/intent del provider.', max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='provider_status',
            field=models.CharField(blank=True, db_index=True, help_text='Estatus técnico devuelto por el provider (approved, pending, rejected, etc.).', max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='pago',
            name='usuario_portal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_portal', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pago',
            name='webhook_last_payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='pago',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('PAGADO', 'Pagado'), ('PARCIAL', 'Parcial'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado'), ('PENDIENTE_REVISION', 'Pendiente revisión')], db_index=True, default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='metodo',
            field=models.CharField(blank=True, choices=[('TARJETA', 'Tarjeta'), ('TRANSFERENCIA', 'Transferencia'), ('EFECTIVO', 'Efectivo'), ('SPEI', 'SPEI'), ('OXXO', 'OXXO'), ('MERCADOPAGO', 'MercadoPago'), ('OTRO', 'Otro')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='moneda',
            field=models.CharField(default='MXN', max_length=10),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(decimal_places=2, help_text='Monto esperado del pago.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='pago',
            name='poliza',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='polizas.poliza'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Referencia visible o interna del pago.', max_length=120),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['estatus', 'fecha_pago'], name='finanzas_pa_estatus_6934d7_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['provider', 'provider_payment_id'], name='finanzas_pa_provide_95deae_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['provider_preference_id'], name='finanzas_pa_provide_2bb9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['referencia'], name='finanzas_pa_referen_10e747_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['fecha_programada'], name='finanzas_pa_fecha_p_75dbe7_idx'),
        ),
        migrations.AddField(
            model_name='pagotransaccion',
            name='pago',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='finanzas.pago'),
        ),
        migrations.AddIndex(
            model_name='pagotransaccion',
            index=models.Index(fields=['provider', 'provider_payment_id'], name='finanzas_pa_provide_0b42f3_idx'),
        ),
        migrations.AddIndex(
            model_name='pagotransaccion',
            index=models.Index(fields=['provider', 'provider_preference_id'], name='finanzas_pa_provide_c0b256_idx'),
        ),
        migrations.AddIndex(
            model_name='pagotransaccion',
            index=models.Index(fields=['tipo', 'created_at'], name='finanzas_pa_tipo_cf0e28_idx'),
        ),
    ]
