# Generated by Django 5.2 on 2026-04-22 19:28

import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0002_pagotransaccion_alter_pago_options_and_more'),
        ('polizas', '0013_alter_polizaevento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comision',
            options={'ordering': ['-fecha_generacion', '-id'], 'permissions': [('manage_comisiones', 'Puede administrar comisiones')], 'verbose_name': 'Comisión', 'verbose_name_plural': 'Comisiones'},
        ),
        migrations.RemoveField(
            model_name='comision',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='comision',
            name='monto',
        ),
        migrations.AddField(
            model_name='comision',
            name='base_calculo',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='comision',
            name='fecha_generacion',
            field=models.DateField(db_index=True, default=django.utils.timezone.localdate),
        ),
        migrations.AddField(
            model_name='comision',
            name='monto_comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='comision',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='comision',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADA', 'Pagada'), ('CANCELADA', 'Cancelada')], db_index=True, default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='comision',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='comision',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='comision',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='comision',
            constraint=models.UniqueConstraint(fields=('poliza', 'agente'), name='uq_comision_poliza_agente'),
        ),
    ]
