# Generated by Django 5.2 on 2026-05-01 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('finanzas', '0003_alter_comision_options_remove_comision_moneda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguimientoCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LLAMADA', 'Llamada'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('PROMESA_PAGO', 'Promesa de pago'), ('NOTA', 'Nota'), ('OTRO', 'Otro')], db_index=True, default='NOTA', max_length=30)),
                ('comentario', models.TextField()),
                ('proxima_accion', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='finanzas.pago')),
            ],
            options={
                'verbose_name': 'Seguimiento de cobranza',
                'verbose_name_plural': 'Seguimientos de cobranza',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionComision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ramo', models.CharField(blank=True, max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.aseguradora')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='catalogos.productoseguro')),
            ],
            options={
                'unique_together': {('aseguradora', 'producto', 'ramo')},
            },
        ),
    ]
