# Generated by Django 5.2 on 2026-01-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autos', '0001_initial'),
        ('catalogos', '0001_initial'),
        ('crm', '0001_initial'),
        ('tarifas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tipo_cotizacion', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('FLOTILLA', 'Flotilla')], db_index=True, max_length=10)),
                ('vigencia_desde', models.DateField(db_index=True)),
                ('vigencia_hasta', models.DateField(db_index=True)),
                ('forma_pago_preferida', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('notas', models.TextField(blank=True, default='')),
                ('estatus', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida')], db_index=True, default='BORRADOR', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='crm.cliente')),
                ('flotilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='autos.flotilla')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='autos.vehiculo')),
            ],
            options={
                'permissions': [('send_cotizacion', 'Puede enviar cotización'), ('approve_cotizacion', 'Puede marcar cotización como aceptada')],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('moneda', models.CharField(db_index=True, default='MXN', max_length=3)),
                ('prima_neta', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('derechos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('recargos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('descuentos', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('iva', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('prima_total', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=14)),
                ('forma_pago', models.CharField(blank=True, default='', max_length=30)),
                ('meses', models.PositiveIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, default='')),
                ('ranking', models.IntegerField(db_index=True, default=0)),
                ('seleccionada', models.BooleanField(db_index=True, default=False)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion_items', to='catalogos.aseguradora')),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cotizador.cotizacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizacion_items', to='catalogos.productoseguro')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionFlotillaItemVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('moneda', models.CharField(db_index=True, default='MXN', max_length=3)),
                ('prima_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('detalle_json', models.JSONField(blank=True, default=dict)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_flotilla', to='autos.vehiculo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flotilla_vehiculos', to='cotizador.cotizacionitem')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionItemCalculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('prima_base', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('factor_total', models.DecimalField(decimal_places=6, default=1, max_digits=14)),
                ('detalle_json', models.JSONField(blank=True, default=dict)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calculo', to='cotizador.cotizacionitem')),
            ],
            options={
                'permissions': [('view_calculo_cotizacion', 'Puede ver detalle de cálculo de cotización')],
            },
        ),
        migrations.CreateModel(
            name='CotizacionItemCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('incluida', models.BooleanField(default=True)),
                ('valor', models.CharField(blank=True, default='', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalogos.coberturacatalogo')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='cotizador.cotizacionitem')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionItemReglaAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('resultado', models.CharField(choices=[('APLICO', 'Aplicó'), ('NO_APLICO', 'No aplicó'), ('RECHAZO', 'Rechazó')], db_index=True, max_length=10)),
                ('valor_resultante', models.CharField(blank=True, default='', max_length=200)),
                ('mensaje', models.TextField(blank=True, default='')),
                ('orden', models.PositiveIntegerField(db_index=True, default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas_aplicadas', to='cotizador.cotizacionitem')),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tarifas.reglatarifa')),
            ],
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['cliente', 'estatus', 'created_at'], name='cotizador_c_cliente_58dfda_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion',
            index=models.Index(fields=['owner', 'estatus'], name='cotizador_c_owner_i_8f1cd1_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizacion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('tipo_cotizacion', 'INDIVIDUAL'), ('vehiculo__isnull', False), ('flotilla__isnull', True)), models.Q(('tipo_cotizacion', 'FLOTILLA'), ('flotilla__isnull', False), ('vehiculo__isnull', True)), _connector='OR'), name='ck_cotizacion_individual_o_flotilla'),
        ),
        migrations.AddIndex(
            model_name='cotizacionitem',
            index=models.Index(fields=['cotizacion', 'ranking'], name='cotizador_c_cotizac_58dcca_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacionitem',
            index=models.Index(fields=['aseguradora', 'producto'], name='cotizador_c_asegura_d8464c_idx'),
        ),
        migrations.AddConstraint(
            model_name='cotizacionitem',
            constraint=models.UniqueConstraint(fields=('cotizacion', 'aseguradora', 'producto'), name='uq_cotizacion_item_unico'),
        ),
        migrations.AddConstraint(
            model_name='cotizacionflotillaitemvehiculo',
            constraint=models.UniqueConstraint(fields=('item', 'vehiculo'), name='uq_item_vehiculo_flotilla'),
        ),
        migrations.AddConstraint(
            model_name='cotizacionitemcobertura',
            constraint=models.UniqueConstraint(fields=('item', 'cobertura'), name='uq_item_cobertura'),
        ),
        migrations.AddIndex(
            model_name='cotizacionitemreglaaplicada',
            index=models.Index(fields=['item', 'orden'], name='cotizador_c_item_id_72cbd3_idx'),
        ),
    ]
