# Generated by Django 5.2 on 2026-01-27 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0002_cotizacion_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioCotizacionCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True)),
                ('last', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='folio',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, unique=True),
        ),
    ]
