# Generated by Django 5.2 on 2026-01-27 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0003_foliocotizacioncounter_cotizacion_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='folio',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20),
        ),
    ]
