# Generated by Django 5.2 on 2026-01-27 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0004_alter_cotizacion_folio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='folio',
            field=models.CharField(blank=True, db_index=True, default='', max_length=20, unique=True),
        ),
    ]
