# Generated by Django 5.2 on 2026-01-27 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0005_alter_cotizacion_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='origen',
            field=models.CharField(choices=[('PORTAL_PUBLICO', 'Portal público'), ('CRM', 'CRM interno'), ('AGENTE', 'Agente'), ('API', 'API')], db_index=True, default='CRM', max_length=20),
        ),
    ]
