# Generated by Django 5.2 on 2026-02-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0006_cotizacion_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago_preferida',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral')], default='CONTADO', max_length=30),
        ),
    ]
