# Generated by Django 5.2 on 2026-02-10 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0007_alter_cotizacion_forma_pago_preferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago_preferida',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral')], db_index=True, default='CONTADO', max_length=30),
        ),
    ]
