# Generated by Django 5.2 on 2026-02-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0008_alter_cotizacion_forma_pago_preferida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacionitem',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral')], db_index=True, default='', help_text='Opcional. Si se define, sobreescribe la forma de pago de la cotización.', max_length=30),
        ),
    ]
