# Generated by Django 5.2 on 2026-05-27 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0009_alter_cotizacionitem_forma_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='emitida_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('Emitida', 'Emitida')], db_index=True, default='BORRADOR', max_length=10),
        ),
    ]
