# Generated by Django 5.2 on 2026-05-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0010_cotizacion_emitida_at_alter_cotizacion_estatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cotizacion',
            name='emitida_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
