# Generated by Django 5.2 on 2026-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0011_alter_cotizacion_emitida_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='codigo_postal',
            field=models.CharField(blank=True, db_index=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
