# Generated by Django 5.2 on 2026-07-07 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0012_cotizacion_ciudad_cotizacion_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacionitem',
            name='paquete_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='provider',
            field=models.CharField(blank=True, db_index=True, default='', max_length=30),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='provider_quote_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='provider_raw_response',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
