# Generated by Django 5.2 on 2026-08-06 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0013_cotizacionitem_paquete_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='conductor_edad',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='conductor_genero',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino')], db_index=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='conductor_nombre',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('ENVIADA', 'Enviada'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada'), ('VENCIDA', 'Vencida'), ('EMITIDA', 'Emitida')], db_index=True, default='BORRADOR', max_length=10),
        ),
    ]
