# Generated by Django 5.2 on 2026-08-09 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0014_cotizacion_conductor_edad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CotizacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('provider_code', models.CharField(db_index=True, max_length=30)),
                ('success', models.BooleanField(db_index=True, default=False)),
                ('elapsed_ms', models.PositiveIntegerField(default=0)),
                ('provider_quote_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('provider_quote_version_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('reference', models.CharField(blank=True, default='', max_length=150)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('net_premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fees', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('taxes', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_premium', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=14, null=True)),
                ('request_json', models.JSONField(blank=True, default=dict)),
                ('response_json', models.JSONField(blank=True, default=dict)),
                ('messages_json', models.JSONField(blank=True, default=list)),
                ('error_message', models.TextField(blank=True, default='')),
                ('error_type', models.CharField(blank=True, default='', max_length=150)),
                ('error_retryable', models.BooleanField(default=False)),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_proveedor', to='cotizador.cotizacion')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionProveedorOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('provider_package_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('total_premium', models.DecimalField(db_index=True, decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(blank=True, default='', max_length=10)),
                ('selected', models.BooleanField(db_index=True, default=False)),
                ('cotizacion_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cotizador.cotizacionproveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionProveedorCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('code', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(blank=True, default='', max_length=200)),
                ('insured_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('deductible', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('premium', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='cotizador.cotizacionproveedoropcion')),
            ],
        ),
        migrations.CreateModel(
            name='CotizacionProveedorRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('reference', models.CharField(blank=True, default='', max_length=150)),
                ('provider_risk_id', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('risk_number', models.PositiveIntegerField(blank=True, null=True)),
                ('vehicle_key', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('cotizacion_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='cotizador.cotizacionproveedor')),
            ],
        ),
        migrations.AddField(
            model_name='cotizacionproveedoropcion',
            name='riesgo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='cotizador.cotizacionproveedorriesgo'),
        ),
        migrations.AddIndex(
            model_name='cotizacionproveedor',
            index=models.Index(fields=['cotizacion', 'provider_code', 'created_at'], name='cotizador_c_cotizac_638c8e_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacionproveedor',
            index=models.Index(fields=['provider_code', 'success'], name='cotizador_c_provide_925068_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacionproveedorcobertura',
            index=models.Index(fields=['opcion', 'code'], name='cotizador_c_opcion__1508d1_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacionproveedorriesgo',
            index=models.Index(fields=['cotizacion_proveedor', 'provider_risk_id'], name='cotizador_c_cotizac_83397e_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacionproveedoropcion',
            index=models.Index(fields=['cotizacion_proveedor', 'selected'], name='cotizador_c_cotizac_eb73d9_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacionproveedoropcion',
            index=models.Index(fields=['riesgo', 'provider_package_id'], name='cotizador_c_riesgo__e92ae8_idx'),
        ),
    ]
