# Generated by Django 5.2 on 2026-08-11 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cotizador', '0015_cotizacionproveedor_cotizacionproveedoropcion_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cotizacionitem',
            name='uq_cotizacion_item_unico',
        ),
        migrations.AddField(
            model_name='cotizacionitem',
            name='provider_option',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizacion_item', to='cotizador.cotizacionproveedoropcion'),
        ),
    ]
