# Generated by Django 5.2 on 2026-01-22 17:46

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=120, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Flotilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nombre_flotilla', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flotillas', to='crm.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='SubMarca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=120)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submarcas', to='autos.marca')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tipo_uso', models.CharField(choices=[('PARTICULAR', 'Particular'), ('COMERCIAL', 'Comercial'), ('PLATAFORMA', 'Plataforma (Uber/Didi)'), ('CARGA', 'Carga'), ('OTRO', 'Otro')], db_index=True, default='PARTICULAR', max_length=15)),
                ('marca_texto', models.CharField(blank=True, default='', max_length=120)),
                ('submarca_texto', models.CharField(blank=True, default='', max_length=120)),
                ('modelo_anio', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('vin', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('serie_motor', models.CharField(blank=True, default='', max_length=40)),
                ('placas', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('color', models.CharField(blank=True, default='', max_length=40)),
                ('tipo_vehiculo', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('valor_comercial', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('adaptaciones', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='crm.cliente')),
            ],
            options={
                'permissions': [('manage_vehiculos', 'Puede administrar vehículos')],
            },
        ),
        migrations.CreateModel(
            name='FlotillaVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('fecha_alta', models.DateField(default=django.utils.timezone.now)),
                ('fecha_baja', models.DateField(blank=True, null=True)),
                ('flotilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='autos.flotilla')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flotillas', to='autos.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='VehiculoCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('anio', models.PositiveIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2100)])),
                ('version', models.CharField(blank=True, default='', max_length=120)),
                ('clave_amis', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('tipo_vehiculo', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('valor_referencia', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_catalogo', to='autos.marca')),
                ('submarca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehiculos_catalogo', to='autos.submarca')),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vehiculos', to='autos.vehiculocatalogo'),
        ),
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('licencia_numero', models.CharField(blank=True, db_index=True, default='', max_length=40)),
                ('licencia_estado', models.CharField(blank=True, default='', max_length=100)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notas', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conductores', to='crm.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'is_active'], name='autos_condu_cliente_bd9ab9_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='flotilla',
            index=models.Index(fields=['cliente', 'is_active'], name='autos_floti_cliente_40f577_idx'),
        ),
        migrations.AddConstraint(
            model_name='flotilla',
            constraint=models.UniqueConstraint(fields=('cliente', 'nombre_flotilla'), name='uq_cliente_flotilla'),
        ),
        migrations.AddConstraint(
            model_name='submarca',
            constraint=models.UniqueConstraint(fields=('marca', 'nombre'), name='uq_marca_submarca'),
        ),
        migrations.AddConstraint(
            model_name='flotillavehiculo',
            constraint=models.UniqueConstraint(fields=('flotilla', 'vehiculo'), name='uq_flotilla_vehiculo'),
        ),
        migrations.AddIndex(
            model_name='vehiculocatalogo',
            index=models.Index(fields=['marca', 'submarca', 'anio'], name='autos_vehic_marca_i_510218_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculocatalogo',
            index=models.Index(fields=['clave_amis'], name='autos_vehic_clave_a_a8534d_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['cliente', 'is_active'], name='autos_vehic_cliente_9d95b7_idx'),
        ),
        migrations.AddIndex(
            model_name='vehiculo',
            index=models.Index(fields=['modelo_anio', 'tipo_uso'], name='autos_vehic_modelo__a85f12_idx'),
        ),
    ]
