# Generated by Django 5.2 on 2026-05-25 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='vin',
            field=models.CharField(blank=True, db_index=True, default='', max_length=17),
        ),
    ]
