# Generated by Django 5.2 on 2026-01-22 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aseguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('rfc', models.CharField(blank=True, default='', max_length=20)),
                ('sitio_web', models.URLField(blank=True, default='')),
                ('telefono_contacto', models.CharField(blank=True, default='', max_length=30)),
                ('email_contacto', models.EmailField(blank=True, default='', max_length=254)),
            ],
            options={
                'permissions': [('manage_aseguradora', 'Puede administrar aseguradoras')],
                'indexes': [models.Index(fields=['is_active', 'nombre'], name='catalogos_a_is_acti_62c85a_idx')],
            },
        ),
        migrations.CreateModel(
            name='CoberturaCatalogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo_valor', models.CharField(choices=[('MONTO', 'Monto'), ('PORCENTAJE', 'Porcentaje'), ('TEXTO', 'Texto'), ('BOOL', 'Sí/No')], db_index=True, default='MONTO', max_length=15)),
            ],
            options={
                'permissions': [('manage_coberturas', 'Puede administrar catálogo de coberturas')],
                'indexes': [models.Index(fields=['is_active', 'codigo'], name='catalogos_c_is_acti_d03ad6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ProductoSeguro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('moneda', models.CharField(db_index=True, default='MXN', max_length=3)),
                ('nombre_producto', models.CharField(max_length=200)),
                ('tipo_producto', models.CharField(choices=[('AUTO', 'Auto'), ('FLOTILLA', 'Flotilla'), ('MOTO', 'Moto'), ('OTRO', 'Otro')], db_index=True, default='AUTO', max_length=20)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('modelo_calculo', models.CharField(choices=[('SIMPLE', 'Captura externa (A)'), ('REGLAS', 'Motor de reglas (B)')], db_index=True, default='REGLAS', max_length=10)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogos.aseguradora')),
            ],
            options={
                'permissions': [('manage_producto_seguro', 'Puede administrar productos/planes')],
            },
        ),
        migrations.CreateModel(
            name='ProductoCobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('incluida', models.BooleanField(default=True)),
                ('valor_default', models.CharField(blank=True, default='', max_length=120)),
                ('notas', models.TextField(blank=True, default='')),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='catalogos.coberturacatalogo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas', to='catalogos.productoseguro')),
            ],
        ),
        migrations.CreateModel(
            name='AseguradoraContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=200)),
                ('puesto', models.CharField(blank=True, default='', max_length=150)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('notas', models.TextField(blank=True, default='')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='catalogos.aseguradora')),
            ],
            options={
                'indexes': [models.Index(fields=['aseguradora', 'is_active'], name='catalogos_a_asegura_fd7098_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productoseguro',
            index=models.Index(fields=['aseguradora', 'is_active'], name='catalogos_p_asegura_28ec88_idx'),
        ),
        migrations.AddIndex(
            model_name='productoseguro',
            index=models.Index(fields=['tipo_producto', 'is_active'], name='catalogos_p_tipo_pr_e33432_idx'),
        ),
        migrations.AddConstraint(
            model_name='productoseguro',
            constraint=models.UniqueConstraint(fields=('aseguradora', 'nombre_producto'), name='uq_producto_por_aseguradora'),
        ),
        migrations.AddConstraint(
            model_name='productocobertura',
            constraint=models.UniqueConstraint(fields=('producto', 'cobertura'), name='uq_producto_cobertura'),
        ),
    ]
