# Generated by Django 5.2 on 2026-01-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('PDF', 'PDF'), ('IMG', 'Imagen'), ('XML', 'XML'), ('DOC', 'Documento'), ('OTRO', 'Otro')], db_index=True, default='OTRO', max_length=10)),
                ('file', models.FileField(upload_to='docs/%Y/%m/')),
                ('tamano', models.PositiveIntegerField(default=0)),
                ('hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('subido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('download_documento', 'Puede descargar documentos')],
            },
        ),
    ]
