# Generated by Django 5.2 on 2026-01-22 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('rol', models.CharField(choices=[('ADMIN', 'Admin'), ('AGENTE', 'Agente'), ('OPERADOR', 'Operador'), ('LECTURA', 'Solo lectura')], db_index=True, default='AGENTE', max_length=10)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('notas', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('aseguradoras_permitidas', models.ManyToManyField(blank=True, related_name='usuarios_permitidos', to='catalogos.aseguradora')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('can_quote', 'Puede cotizar'), ('can_issue_policy', 'Puede emitir póliza'), ('can_cancel_policy', 'Puede cancelar póliza'), ('can_manage_tariffs', 'Puede administrar tarifas y reglas'), ('can_view_finance', 'Puede ver finanzas (pagos/comisiones)'), ('can_manage_finance', 'Puede administrar finanzas (pagos/comisiones)')],
            },
        ),
    ]
