# Generated by Django 5.2 on 2026-04-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('SUPERVISOR', 'Supervisor'), ('AGENTE', 'Agente'), ('OPERADOR', 'Operador'), ('LECTURA', 'Solo lectura')], db_index=True, default='AGENTE', max_length=10),
        ),
    ]
