# Generated by Django 5.2 on 2026-05-01 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_rol'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('can_quote', 'Puede cotizar'), ('can_issue_policy', 'Puede emitir póliza'), ('can_cancel_policy', 'Puede cancelar póliza'), ('can_manage_tariffs', 'Puede administrar tarifas y reglas'), ('can_view_finance', 'Puede ver finanzas (pagos/comisiones)'), ('can_manage_finance', 'Puede administrar finanzas (pagos/comisiones)'), ('view_reportes', 'Puede ver reportes'), ('view_cobranza', 'Puede ver cobranza'), ('manage_comisiones', 'Puede administrar comisiones'), ('manage_pagos', 'Puede administrar pagos'), ('emitir_poliza', 'Puede emitir pólizas')]},
        ),
    ]
