# Generated by Django 5.2 on 2026-01-22 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('calle', models.CharField(blank=True, default='', max_length=200)),
                ('num_ext', models.CharField(blank=True, default='', max_length=20)),
                ('num_int', models.CharField(blank=True, default='', max_length=20)),
                ('colonia', models.CharField(blank=True, default='', max_length=150)),
                ('ciudad', models.CharField(blank=True, default='', max_length=150)),
                ('estado', models.CharField(blank=True, default='', max_length=150)),
                ('cp', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('pais', models.CharField(blank=True, default='México', max_length=80)),
                ('referencias', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tipo_cliente', models.CharField(choices=[('PERSONA', 'Persona'), ('EMPRESA', 'Empresa')], db_index=True, max_length=10)),
                ('nombre_comercial', models.CharField(blank=True, default='', max_length=200)),
                ('nombre', models.CharField(blank=True, default='', max_length=120)),
                ('apellido_paterno', models.CharField(blank=True, default='', max_length=120)),
                ('apellido_materno', models.CharField(blank=True, default='', max_length=120)),
                ('rfc', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('curp', models.CharField(blank=True, default='', max_length=25)),
                ('email_principal', models.EmailField(blank=True, db_index=True, default='', max_length=254)),
                ('telefono_principal', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('estatus', models.CharField(choices=[('PROSPECTO', 'Prospecto'), ('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], db_index=True, default='PROSPECTO', max_length=12)),
                ('origen', models.CharField(blank=True, db_index=True, default='', max_length=80)),
                ('notas', models.TextField(blank=True, default='')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_asignados', to=settings.AUTH_USER_MODEL)),
                ('direccion_contacto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_contacto', to='crm.direccion')),
                ('direccion_fiscal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_fiscal', to='crm.direccion')),
            ],
            options={
                'permissions': [('manage_clientes', 'Puede administrar clientes'), ('reassign_cliente_owner', 'Puede reasignar cartera de clientes')],
            },
        ),
        migrations.CreateModel(
            name='Conversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('asunto', models.CharField(max_length=200)),
                ('canal_principal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('LLAMADA', 'Llamada'), ('SMS', 'SMS'), ('PRESENCIAL', 'Presencial'), ('OTRO', 'Otro')], db_index=True, default='WHATSAPP', max_length=12)),
                ('relacionado_tipo', models.CharField(blank=True, db_index=True, default='', max_length=20)),
                ('relacionado_id', models.PositiveIntegerField(blank=True, db_index=True, null=True)),
                ('estatus', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], db_index=True, default='ABIERTA', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones', to='crm.cliente')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversaciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('fecha_hora', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('canal', models.CharField(choices=[('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('LLAMADA', 'Llamada'), ('SMS', 'SMS'), ('PRESENCIAL', 'Presencial'), ('OTRO', 'Otro')], db_index=True, max_length=12)),
                ('direccion', models.CharField(choices=[('SALIENTE', 'Saliente'), ('ENTRANTE', 'Entrante')], db_index=True, max_length=10)),
                ('contenido', models.TextField()),
                ('leido', models.BooleanField(db_index=True, default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('archivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to='documentos.documento')),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='crm.conversacion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ClienteContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=200)),
                ('rol', models.CharField(blank=True, default='', max_length=120)),
                ('telefono', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('preferido', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True, default='')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='crm.cliente')),
            ],
            options={
                'indexes': [models.Index(fields=['cliente', 'is_active'], name='crm_cliente_cliente_0c3f1f_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['cliente', 'estatus', 'updated_at'], name='crm_convers_cliente_6d7deb_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tipo_cliente', 'estatus', 'is_active'], name='crm_cliente_tipo_cl_0e2300_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['owner', 'is_active'], name='crm_cliente_owner_i_9d6aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'fecha_hora'], name='crm_mensaje_convers_c41f97_idx'),
        ),
    ]
