# Generated by Django 5.2 on 2026-01-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_cliente_user_portal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='portal_activo',
            field=models.BooleanField(default=True),
        ),
    ]
