# Generated by Django 5.2 on 2026-01-31 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_cliente_contacto_email_cliente_contacto_nombre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('manage_clientes', 'Puede administrar clientes'), ('reassign_cliente_owner', 'Puede reasignar cartera de clientes'), ('toggle_portal_activo', 'Puede activar/desactivar portal de clientes')]},
        ),
    ]
