# Generated by Django 5.2 on 2026-01-31 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_cliente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'permissions': [('manage_clientes', 'Puede administrar clientes'), ('reassign_cliente_owner', 'Puede reasignar cartera de clientes'), ('manage_portal_activo', 'Puede activar/desactivar portal de clientes')]},
        ),
    ]
