# Generated by Django 5.2 on 2026-06-09 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_cliente_codigo_postal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoPostal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_postal', models.CharField(blank=True, db_index=True, default='', max_length=5)),
                ('colonia', models.CharField(blank=True, default='', max_length=60)),
                ('municipio', models.CharField(blank=True, default='', max_length=50)),
                ('ciudad', models.CharField(blank=True, default='', max_length=60)),
                ('estado', models.CharField(blank=True, default='', max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, db_index=True, default='', max_length=5),
        ),
    ]
