# Generated by Django 5.2 on 2026-02-20 20:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(db_index=True, max_length=30)),
                ('provider_event_id', models.CharField(db_index=True, max_length=120)),
                ('event_type', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('status', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('PROCESADO', 'Procesado'), ('IGNORADO', 'Ignorado'), ('FALLO', 'Fallo')], db_index=True, default='RECIBIDO', max_length=12)),
                ('payload', models.JSONField()),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['provider', 'status', 'received_at'], name='integration_provide_7ccdb5_idx')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='uq_integration_event_dedupe')],
            },
        ),
    ]
