# Generated by Django 5.2 on 2026-02-21 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='integrationevent',
            options={'ordering': ['-received_at', '-id']},
        ),
        migrations.RemoveConstraint(
            model_name='integrationevent',
            name='uq_integration_event_dedupe',
        ),
        migrations.RenameField(
            model_name='integrationevent',
            old_name='error',
            new_name='error_message',
        ),
        migrations.RenameField(
            model_name='integrationevent',
            old_name='provider_event_id',
            new_name='event_id',
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Clave interna opcional (ej: PAGO_PAGADO:123). Complementa event_id.', max_length=160, null=True),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='error_trace',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='headers',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='object_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='object_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='raw_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='response_body',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='integrationevent',
            name='signature',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='integrationevent',
            name='event_type',
            field=models.CharField(blank=True, db_index=True, default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='integrationevent',
            name='payload',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationevent',
            name='processed_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='integrationevent',
            name='provider',
            field=models.CharField(db_index=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='integrationevent',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Recibido'), ('PROCESSED', 'Procesado'), ('IGNORED', 'Ignorado'), ('ERROR', 'Error')], db_index=True, default='RECEIVED', max_length=12),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['provider', 'event_type', 'received_at'], name='integration_provide_e43418_idx'),
        ),
        migrations.AddConstraint(
            model_name='integrationevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='uq_integration_event_provider_event_id'),
        ),
        migrations.AddConstraint(
            model_name='integrationevent',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('provider', 'dedupe_key'), name='uq_integration_event_provider_dedupe_key'),
        ),
    ]
