# Generated by Django 5.2 on 2026-06-29 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_alter_integrationevent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AseguradoraConfiguracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('CHUBB', 'Chubb'), ('AXA', 'Axa'), ('QUALITAS', 'Qualitas'), ('GNP', 'Gnp'), ('GENERAL', 'General')], max_length=30)),
                ('ambiente', models.CharField(choices=[('SIT', 'SIT'), ('UAT', 'UAT'), ('PROD', 'Producción')], default='SIT', max_length=20)),
                ('nombre', models.CharField(max_length=120)),
                ('activo', models.BooleanField(default=True)),
                ('token_url', models.URLField()),
                ('base_url', models.URLField()),
                ('client_id', models.CharField(max_length=200)),
                ('client_secret', models.TextField()),
                ('resource_id', models.CharField(max_length=200)),
                ('api_version', models.CharField(default='1', max_length=10)),
                ('timeout', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de aseguradora',
                'verbose_name_plural': 'Configuraciones de aseguradoras',
                'unique_together': {('provider', 'ambiente', 'resource_id')},
            },
        ),
    ]
