# Generated by Django 5.2 on 2026-07-10 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
        ('integrations', '0003_aseguradoraconfiguracion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.TextField(blank=True, default='')),
                ('value_type', models.CharField(choices=[('STRING', 'Texto'), ('INTEGER', 'Entero'), ('DECIMAL', 'Decimal'), ('BOOLEAN', 'Booleano'), ('JSON', 'JSON')], default='STRING', max_length=20)),
                ('descripcion', models.CharField(blank=True, default='', max_length=255)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parámetro del Provider',
                'verbose_name_plural': 'Parámetros de Providers',
                'ordering': ['key'],
            },
        ),
        migrations.AlterModelOptions(
            name='aseguradoraconfiguracion',
            options={'ordering': ['prioridad', 'provider'], 'verbose_name': 'Configuración de aseguradora', 'verbose_name_plural': 'Configuraciones de aseguradoras'},
        ),
        migrations.AlterUniqueTogether(
            name='aseguradoraconfiguracion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='aseguradora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='configuraciones_api', to='catalogos.aseguradora'),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='prioridad',
            field=models.PositiveIntegerField(db_index=True, default=100),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='ramo',
            field=models.CharField(choices=[('AUTOS', 'Autos'), ('FLOTILLAS', 'Flotillas'), ('MOTOS', 'Motos'), ('HOGAR', 'Hogar'), ('VIDA', 'Vida'), ('OTRO', 'Otro')], db_index=True, default='AUTOS', max_length=30),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='supports_cancellation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='supports_documents',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='supports_endorsements',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='supports_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='supports_payments',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='supports_quote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='supports_renewal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aseguradoraconfiguracion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='aseguradoraconfiguracion',
            name='ambiente',
            field=models.CharField(choices=[('SIT', 'SIT'), ('UAT', 'UAT'), ('PROD', 'Producción')], db_index=True, default='SIT', max_length=20),
        ),
        migrations.AlterField(
            model_name='aseguradoraconfiguracion',
            name='client_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aseguradoraconfiguracion',
            name='client_secret',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='aseguradoraconfiguracion',
            name='provider',
            field=models.CharField(choices=[('CHUBB', 'Chubb'), ('AXA', 'AXA'), ('QUALITAS', 'Quálitas'), ('GNP', 'GNP'), ('GENERAL', 'General')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='aseguradoraconfiguracion',
            name='resource_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='aseguradoraconfiguracion',
            name='token_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='aseguradoraconfiguracion',
            index=models.Index(fields=['provider', 'ambiente', 'activo'], name='idx_provider_env_active'),
        ),
        migrations.AddIndex(
            model_name='aseguradoraconfiguracion',
            index=models.Index(fields=['ramo', 'activo', 'prioridad'], name='idx_provider_ramo_priority'),
        ),
        migrations.AddConstraint(
            model_name='aseguradoraconfiguracion',
            constraint=models.UniqueConstraint(fields=('provider', 'ambiente', 'ramo', 'resource_id'), name='uq_provider_config_env_ramo_resource'),
        ),
        migrations.AddField(
            model_name='providersetting',
            name='configuracion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='integrations.aseguradoraconfiguracion'),
        ),
        migrations.AddIndex(
            model_name='providersetting',
            index=models.Index(fields=['configuracion', 'activo'], name='idx_provider_setting_active'),
        ),
        migrations.AddConstraint(
            model_name='providersetting',
            constraint=models.UniqueConstraint(fields=('configuracion', 'key'), name='uq_provider_setting_config_key'),
        ),
    ]
