# Generated by Django 5.2 on 2026-07-11 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_catalog_catalogitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderCatalogMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_code', models.CharField(max_length=200, verbose_name='Código externo')),
                ('external_name', models.CharField(blank=True, default='', max_length=250, verbose_name='Nombre externo')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_mappings', to='integrations.catalog', verbose_name='Catálogo')),
                ('catalog_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provider_mappings', to='integrations.catalogitem', verbose_name='Elemento de catálogo')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catalog_mappings', to='integrations.aseguradoraconfiguracion', verbose_name='Configuración de aseguradora')),
            ],
            options={
                'verbose_name': 'Mapeo de catálogo por provider',
                'verbose_name_plural': 'Mapeos de catálogo por provider',
                'ordering': ['provider', 'catalog', 'catalog_item__sort_order', 'catalog_item__name'],
                'indexes': [models.Index(fields=['provider', 'catalog', 'is_active'], name='idx_provider_catalog_active')],
                'constraints': [models.UniqueConstraint(fields=('provider', 'catalog_item'), name='uq_provider_catalog_item'), models.UniqueConstraint(fields=('provider', 'catalog', 'external_code'), name='uq_provider_catalog_external_code')],
            },
        ),
    ]
