# Generated by Django 5.2 on 2026-07-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_providercatalogmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='business_profile_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='grouping_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='rate_id',
            field=models.PositiveBigIntegerField(blank=True, help_text='Identificador de tarifa asignado por la aseguradora.', null=True),
        ),
    ]
