# Generated by Django 5.2 on 2026-08-03 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0007_aseguradoraconfiguracion_business_profile_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='business_profile_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aseguradoraconfiguracion',
            name='source_application_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
