# Generated by Django 5.2 on 2026-01-22 17:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('autos', '0001_initial'),
        ('catalogos', '0001_initial'),
        ('cotizador', '0001_initial'),
        ('crm', '0001_initial'),
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tipo_incidente', models.CharField(choices=[('CHOQUE', 'Choque'), ('ROBO', 'Robo'), ('DANIOS', 'Daños'), ('RC', 'Responsabilidad civil'), ('INFRACCION', 'Infracción'), ('OTRO', 'Otro')], db_index=True, max_length=15)),
                ('fecha_incidente', models.DateField(db_index=True)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('monto_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('resolucion', models.TextField(blank=True, default='')),
                ('estatus', models.CharField(choices=[('ABIERTO', 'Abierto'), ('CERRADO', 'Cerrado')], db_index=True, default='ABIERTO', max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='crm.cliente')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='autos.conductor')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='documentos.documento')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes', to='autos.vehiculo')),
            ],
            options={
                'permissions': [('manage_incidentes', 'Puede administrar incidentes')],
            },
        ),
        migrations.CreateModel(
            name='Poliza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('moneda', models.CharField(db_index=True, default='MXN', max_length=3)),
                ('numero_poliza', models.CharField(db_index=True, max_length=80)),
                ('vigencia_desde', models.DateField(db_index=True)),
                ('vigencia_hasta', models.DateField(db_index=True)),
                ('estatus', models.CharField(choices=[('EN_PROCESO', 'En proceso'), ('VIGENTE', 'Vigente'), ('VENCIDA', 'Vencida'), ('CANCELADA', 'Cancelada')], db_index=True, default='EN_PROCESO', max_length=12)),
                ('prima_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('forma_pago', models.CharField(blank=True, default='', max_length=30)),
                ('agente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to=settings.AUTH_USER_MODEL)),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='catalogos.aseguradora')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='crm.cliente')),
                ('cotizacion_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='cotizador.cotizacionitem')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='documentos.documento')),
                ('flotilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='autos.flotilla')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='polizas', to='catalogos.productoseguro')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polizas', to='autos.vehiculo')),
            ],
            options={
                'permissions': [('manage_polizas', 'Puede administrar pólizas'), ('renew_poliza', 'Puede renovar póliza')],
            },
        ),
        migrations.CreateModel(
            name='Endoso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tipo_endoso', models.CharField(choices=[('CAMBIO_DATOS', 'Cambio de datos'), ('CAMBIO_VEHICULO', 'Cambio de vehículo'), ('AUMENTO_COBERTURA', 'Aumento cobertura'), ('OTRO', 'Otro')], db_index=True, max_length=20)),
                ('fecha', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('prima_ajuste', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='endosos', to='documentos.documento')),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='endosos', to='polizas.poliza')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Renovacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('fecha_renovacion', models.DateField(db_index=True, default=django.utils.timezone.now)),
                ('resultado', models.CharField(blank=True, db_index=True, default='', max_length=30)),
                ('poliza_anterior', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renovaciones_salientes', to='polizas.poliza')),
                ('poliza_nueva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renovaciones_entrantes', to='polizas.poliza')),
            ],
        ),
        migrations.CreateModel(
            name='Siniestro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('numero_siniestro', models.CharField(blank=True, db_index=True, default='', max_length=60)),
                ('fecha_reporte', models.DateField(db_index=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('REPORTADO', 'Reportado'), ('EN_PROCESO', 'En proceso'), ('PAGADO', 'Pagado'), ('RECHAZADO', 'Rechazado'), ('CERRADO', 'Cerrado')], db_index=True, default='REPORTADO', max_length=12)),
                ('monto_reclamado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('notas', models.TextField(blank=True, default='')),
                ('aseguradora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='siniestros', to='catalogos.aseguradora')),
                ('documento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros', to='documentos.documento')),
                ('incidente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='siniestros', to='polizas.incidente')),
            ],
        ),
        migrations.AddIndex(
            model_name='incidente',
            index=models.Index(fields=['cliente', 'fecha_incidente'], name='polizas_inc_cliente_405e2d_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['cliente', 'estatus'], name='polizas_pol_cliente_cfc092_idx'),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['vigencia_hasta', 'estatus'], name='polizas_pol_vigenci_f832ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.UniqueConstraint(fields=('aseguradora', 'numero_poliza'), name='uq_poliza_por_aseguradora'),
        ),
        migrations.AddConstraint(
            model_name='poliza',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('flotilla__isnull', True), ('vehiculo__isnull', False)), models.Q(('flotilla__isnull', False), ('vehiculo__isnull', True)), _connector='OR'), name='ck_poliza_individual_o_flotilla'),
        ),
        migrations.AddConstraint(
            model_name='renovacion',
            constraint=models.UniqueConstraint(fields=('poliza_anterior', 'poliza_nueva'), name='uq_renovacion_unica'),
        ),
        migrations.AddIndex(
            model_name='siniestro',
            index=models.Index(fields=['aseguradora', 'estatus'], name='polizas_sin_asegura_b9ecff_idx'),
        ),
        migrations.AddIndex(
            model_name='siniestro',
            index=models.Index(fields=['fecha_reporte'], name='polizas_sin_fecha_r_18c12d_idx'),
        ),
    ]
