# Generated by Django 5.2 on 2026-02-06 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autos', '0001_initial'),
        ('catalogos', '0001_initial'),
        ('cotizador', '0006_cotizacion_origen'),
        ('crm', '0006_alter_cliente_options'),
        ('documentos', '0001_initial'),
        ('polizas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='fecha_emision',
            field=models.DateField(blank=True, db_index=True, help_text='Fecha en que la póliza fue emitida', null=True),
        ),
        migrations.AddIndex(
            model_name='poliza',
            index=models.Index(fields=['fecha_emision', 'estatus'], name='polizas_pol_fecha_e_3d9f58_idx'),
        ),
    ]
