# Generated by Django 5.2 on 2026-02-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0002_poliza_fecha_emision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poliza',
            name='fecha_cancelacion',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='poliza',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='poliza',
            name='motivo_cancelacion_detalle',
            field=models.TextField(blank=True, default=''),
        ),
    ]
