# Generated by Django 5.2 on 2026-02-07 01:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0003_poliza_fecha_cancelacion_poliza_motivo_cancelacion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('FALTA_PAGO', 'Falta de pago'), ('SOLICITUD_CLIENTE', 'Solicitud del cliente'), ('ERROR_EMISION', 'Error en emisión'), ('CAMBIO_ASEGURADORA', 'Cambio de aseguradora'), ('OTRO', 'Otro')], default='', max_length=30),
        ),
        migrations.CreateModel(
            name='PolizaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('CREADA', 'Creada'), ('NUMERO_ACTUALIZADO', 'Número actualizado'), ('VIGENCIA_ACTUALIZADA', 'Vigencia actualizada'), ('MARCADA_VIGENTE', 'Marcada como vigente'), ('CANCELADA', 'Cancelada'), ('RENOVADA', 'Renovada')], db_index=True, max_length=40)),
                ('titulo', models.CharField(blank=True, default='', max_length=120)),
                ('detalle', models.TextField(blank=True, default='')),
                ('data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('poliza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='polizas.poliza')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
