# Generated by Django 5.2 on 2026-02-09 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0004_alter_poliza_motivo_cancelacion_polizaevento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral')], default='CONTADO', max_length=30),
        ),
    ]
