# Generated by Django 5.2 on 2026-02-10 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0005_alter_poliza_forma_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poliza',
            name='forma_pago',
            field=models.CharField(blank=True, choices=[('CONTADO', 'Contado'), ('MENSUAL', 'Mensual'), ('TRIMESTRAL', 'Trimestral'), ('SEMESTRAL', 'Semestral')], db_index=True, default='CONTADO', max_length=30),
        ),
    ]
