# Generated by Django 5.2 on 2026-02-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0007_alter_polizaevento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polizaevento',
            name='tipo',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('NUMERO_ACTUALIZADO', 'Número actualizado'), ('VIGENCIA_ACTUALIZADA', 'Vigencia actualizada'), ('MARCADA_VIGENTE', 'Marcada como vigente'), ('CANCELADA', 'Cancelada'), ('RENOVADA', 'Renovada'), ('PAGO_VENCIDO', 'Pago vencido'), ('PAGO_PAGADO', 'Pago pagado'), ('PAGO_CANCELADO', 'Pago cancelado')], db_index=True, max_length=40),
        ),
    ]
