# Generated by Django 5.2 on 2026-02-20 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0009_alter_polizaevento_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='polizaevento',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, default=None, help_text='Clave para evitar duplicados. Ej: PAGO_VENCIDO:123', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='polizaevento',
            name='tipo',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('NUMERO_ACTUALIZADO', 'Número actualizado'), ('VIGENCIA_ACTUALIZADA', 'Vigencia actualizada'), ('MARCADA_VIGENTE', 'Marcada como vigente'), ('CANCELADA', 'Cancelada'), ('RENOVADA', 'Renovada'), ('PAGO_VENCIDO', 'Pago vencido'), ('PAGO_PAGADO', 'Pago pagado'), ('PAGO_CANCELADO', 'Pago cancelado'), ('PAGO_COMPROBANTE_ADJUNTADO', 'Comprobante de pago adjuntado'), ('POLIZA_DOCUMENTO_ADJUNTADO', 'Documento de póliza adjuntado'), ('POLIZA_VENCIDA', 'Póliza Vencida')], db_index=True, max_length=40),
        ),
        migrations.AddConstraint(
            model_name='polizaevento',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key__isnull', False)), fields=('poliza', 'tipo', 'dedupe_key'), name='uq_poliza_event_dedupe_key'),
        ),
    ]
