# Generated by Django 5.2 on 2026-02-21 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0010_polizaevento_dedupe_key_alter_polizaevento_tipo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polizaevento',
            name='tipo',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('NUMERO_ACTUALIZADO', 'Número actualizado'), ('VIGENCIA_ACTUALIZADA', 'Vigencia actualizada'), ('MARCADA_VIGENTE', 'Marcada como vigente'), ('CANCELADA', 'Cancelada'), ('RENOVADA', 'Renovada'), ('PAGO_VENCIDO', 'Pago vencido'), ('PAGO_PAGADO', 'Pago pagado'), ('PAGO_CANCELADO', 'Pago cancelado'), ('PAGO_RECHAZADO', 'Pago rechazado'), ('PAGO_COMPROBANTE_ADJUNTADO', 'Comprobante de pago adjuntado'), ('POLIZA_DOCUMENTO_ADJUNTADO', 'Documento de póliza adjuntado'), ('POLIZA_VENCIDA', 'Póliza Vencida')], db_index=True, max_length=40),
        ),
    ]
