# Generated by Django 5.2 on 2026-04-21 20:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0011_alter_polizaevento_tipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='endoso',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Endoso', 'verbose_name_plural': 'Endosos'},
        ),
        migrations.AddField(
            model_name='endoso',
            name='estatus',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('APLICADO', 'Aplicado'), ('CANCELADO', 'Cancelado')], db_index=True, default='APLICADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='endoso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='endoso',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='endoso',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='endoso',
            name='prima_ajuste',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='endoso',
            name='tipo_endoso',
            field=models.CharField(choices=[('CAMBIO_VEHICULO', 'Cambio de vehículo'), ('CAMBIO_COBERTURA', 'Cambio de cobertura'), ('CAMBIO_FORMA_PAGO', 'Cambio de forma de pago'), ('CAMBIO_DATOS', 'Cambio de datos'), ('CANCELACION_PARCIAL', 'Cancelación parcial'), ('OTRO', 'Otro')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='endoso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='polizaevento',
            name='tipo',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('NUMERO_ACTUALIZADO', 'Número actualizado'), ('VIGENCIA_ACTUALIZADA', 'Vigencia actualizada'), ('MARCADA_VIGENTE', 'Marcada como vigente'), ('CANCELADA', 'Cancelada'), ('RENOVADA', 'Renovada'), ('PAGO_VENCIDO', 'Pago vencido'), ('PAGO_PAGADO', 'Pago pagado'), ('PAGO_CANCELADO', 'Pago cancelado'), ('PAGO_RECHAZADO', 'Pago rechazado'), ('PAGO_COMPROBANTE_ADJUNTADO', 'Comprobante de pago adjuntado'), ('POLIZA_DOCUMENTO_ADJUNTADO', 'Documento de póliza adjuntado'), ('POLIZA_VENCIDA', 'Póliza Vencida'), ('PAGO_COMPROBANTE_REEMPLAZADO', 'Comprobante reemplazado'), ('PAGO_RECORDATORIO_ENVIADO', 'Recordatorio enviado'), ('ENDOSO', 'Endoso aplicado')], db_index=True, max_length=40),
        ),
    ]
