# Generated by Django 5.2 on 2026-04-22 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polizas', '0012_alter_endoso_options_endoso_estatus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polizaevento',
            name='tipo',
            field=models.CharField(choices=[('CREADA', 'Creada'), ('NUMERO_ACTUALIZADO', 'Número actualizado'), ('VIGENCIA_ACTUALIZADA', 'Vigencia actualizada'), ('MARCADA_VIGENTE', 'Marcada como vigente'), ('CANCELADA', 'Cancelada'), ('RENOVADA', 'Renovada'), ('PAGO_VENCIDO', 'Pago vencido'), ('PAGO_PAGADO', 'Pago pagado'), ('PAGO_CANCELADO', 'Pago cancelado'), ('PAGO_RECHAZADO', 'Pago rechazado'), ('PAGO_COMPROBANTE_ADJUNTADO', 'Comprobante de pago adjuntado'), ('POLIZA_DOCUMENTO_ADJUNTADO', 'Documento de póliza adjuntado'), ('POLIZA_VENCIDA', 'Póliza Vencida'), ('PAGO_COMPROBANTE_REEMPLAZADO', 'Comprobante reemplazado'), ('PAGO_RECORDATORIO_ENVIADO', 'Recordatorio enviado'), ('ENDOSO', 'Endoso aplicado'), ('ENDOSO_COMPROBANTE_ADJUNTADO', 'Comprobante de Endoso adjuntado'), ('ENDOSO_ELIMINADO', 'Endoso Eliminado'), ('ENDOSO_EDITADO', 'Endoso Editado'), ('COMISION_GENERADA', 'Comisión generada'), ('COMISION_PAGADA', 'Comisión pagada'), ('COMISION_CANCELADA', 'Comisión cancelada')], db_index=True, max_length=40),
        ),
    ]
