# Generated by Django 5.2 on 2026-01-22 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TablaFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('tipo', models.CharField(choices=[('FACTOR', 'Factor'), ('MONTO', 'Monto'), ('PORCENTAJE', 'Porcentaje')], db_index=True, default='FACTOR', max_length=12)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ZonaTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReglaTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_regla', models.CharField(choices=[('ELEGIBILIDAD', 'Elegibilidad'), ('PRIMA_BASE', 'Prima base'), ('FACTOR', 'Factor'), ('RECARGO', 'Recargo'), ('DESCUENTO', 'Descuento'), ('DERECHOS', 'Derechos'), ('AJUSTE_COBERTURA', 'Ajuste cobertura')], db_index=True, max_length=20)),
                ('modo_aplicacion', models.CharField(choices=[('PRIMER_MATCH', 'Primer match'), ('SUMAR_TODAS', 'Sumar todas'), ('MULTIPLICAR_TODAS', 'Multiplicar todas')], default='PRIMER_MATCH', max_length=20)),
                ('prioridad', models.IntegerField(db_index=True, default=0)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='catalogos.productoseguro')),
            ],
            options={
                'permissions': [('manage_reglas_tarifa', 'Puede administrar reglas de tarifa')],
            },
        ),
        migrations.CreateModel(
            name='ReglaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('tipo_accion', models.CharField(choices=[('SET_MONTO', 'Set monto'), ('SET_FACTOR', 'Set factor'), ('SUMAR_MONTO', 'Sumar monto'), ('APLICAR_TABLA_FACTOR', 'Aplicar tabla factor'), ('SET_PORCENTAJE', 'Set %'), ('RECHAZAR', 'Rechazar')], db_index=True, max_length=22)),
                ('variable_destino', models.CharField(blank=True, db_index=True, default='', max_length=50)),
                ('valor', models.DecimalField(blank=True, decimal_places=6, max_digits=14, null=True)),
                ('valor_texto', models.CharField(blank=True, default='', max_length=200)),
                ('redondeo', models.CharField(choices=[('NO', 'No'), ('2_DEC', '2 dec'), ('ENTERO', 'Entero')], default='NO', max_length=10)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('orden', models.PositiveIntegerField(db_index=True, default=1)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='tarifas.reglatarifa')),
                ('tabla_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='acciones', to='tarifas.tablafactor')),
            ],
        ),
        migrations.CreateModel(
            name='CoberturaTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('modo_costo', models.CharField(choices=[('FIJO', 'Fijo'), ('PORC_PRIMA_BASE', '% prima base'), ('PORC_VALOR_VEH', '% valor veh'), ('TABLA_FACTOR', 'Tabla factor')], db_index=True, max_length=20)),
                ('monto_fijo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cobertura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tarifas', to='catalogos.coberturacatalogo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coberturas_tarifa', to='catalogos.productoseguro')),
                ('tabla_factor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='coberturas', to='tarifas.tablafactor')),
            ],
        ),
        migrations.CreateModel(
            name='VariableTarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('tipo_dato', models.CharField(choices=[('INT', 'Entero'), ('DECIMAL', 'Decimal'), ('TEXT', 'Texto'), ('BOOL', 'Sí/No'), ('DATE', 'Fecha')], db_index=True, max_length=10)),
                ('origen', models.CharField(choices=[('CLIENTE', 'Cliente'), ('VEHICULO', 'Vehículo'), ('CONDUCTOR', 'Conductor'), ('COTIZACION', 'Cotización'), ('SISTEMA', 'Sistema')], db_index=True, max_length=12)),
                ('descripcion', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['is_active', 'origen', 'codigo'], name='tarifas_var_is_acti_cfdb63_idx')],
            },
        ),
        migrations.CreateModel(
            name='TablaFactorRango',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('var1_min', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('var1_max', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('var2_min', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('var2_max', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('valor', models.DecimalField(decimal_places=6, max_digits=14)),
                ('prioridad', models.PositiveIntegerField(db_index=True, default=0)),
                ('tabla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rangos', to='tarifas.tablafactor')),
                ('var1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabla_rango_var1', to='tarifas.variabletarifa')),
                ('var2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tabla_rango_var2', to='tarifas.variabletarifa')),
            ],
        ),
        migrations.CreateModel(
            name='ReglaCondicion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('operador', models.CharField(choices=[('=', '='), ('!=', '!='), ('>', '>'), ('>=', '>='), ('<', '<'), ('<=', '<='), ('IN', 'IN'), ('NOT_IN', 'NOT IN'), ('BETWEEN', 'BETWEEN'), ('CONTAINS', 'CONTAINS')], max_length=10)),
                ('valor1', models.CharField(max_length=200)),
                ('valor2', models.CharField(blank=True, default='', max_length=200)),
                ('negada', models.BooleanField(default=False)),
                ('grupo', models.PositiveIntegerField(db_index=True, default=1)),
                ('orden', models.PositiveIntegerField(db_index=True, default=1)),
                ('regla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condiciones', to='tarifas.reglatarifa')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='condiciones', to='tarifas.variabletarifa')),
            ],
        ),
        migrations.CreateModel(
            name='ZonaTarifaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('pais', models.CharField(blank=True, default='México', max_length=80)),
                ('estado', models.CharField(blank=True, default='', max_length=150)),
                ('ciudad', models.CharField(blank=True, default='', max_length=150)),
                ('cp_inicio', models.CharField(blank=True, default='', max_length=10)),
                ('cp_fin', models.CharField(blank=True, default='', max_length=10)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='tarifas.zonatarifa')),
            ],
        ),
        migrations.CreateModel(
            name='DeducibleOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('tipo', models.CharField(choices=[('DM', 'Daños materiales'), ('RT', 'Robo total'), ('RC', 'Resp. civil'), ('OTRO', 'Otro')], db_index=True, max_length=10)),
                ('valor', models.DecimalField(decimal_places=4, max_digits=12)),
                ('es_porcentaje', models.BooleanField(default=True)),
                ('afecta_prima', models.BooleanField(default=True)),
                ('factor_prima', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deducibles', to='catalogos.productoseguro')),
            ],
            options={
                'indexes': [models.Index(fields=['producto', 'tipo', 'is_active'], name='tarifas_ded_product_1fe920_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='reglatarifa',
            index=models.Index(fields=['producto', 'tipo_regla', 'prioridad', 'is_active'], name='tarifas_reg_product_c9a78b_idx'),
        ),
        migrations.AddIndex(
            model_name='reglaaccion',
            index=models.Index(fields=['regla', 'orden'], name='tarifas_reg_regla_i_41c993_idx'),
        ),
        migrations.AddConstraint(
            model_name='coberturatarifa',
            constraint=models.UniqueConstraint(fields=('producto', 'cobertura'), name='uq_producto_cobertura_tarifa'),
        ),
        migrations.AddIndex(
            model_name='tablafactorrango',
            index=models.Index(fields=['tabla', 'is_active', 'prioridad'], name='tarifas_tab_tabla_i_21b1d4_idx'),
        ),
        migrations.AddIndex(
            model_name='tablafactorrango',
            index=models.Index(fields=['var1', 'var2'], name='tarifas_tab_var1_id_ef5c38_idx'),
        ),
        migrations.AddIndex(
            model_name='reglacondicion',
            index=models.Index(fields=['regla', 'grupo', 'orden'], name='tarifas_reg_regla_i_b47d81_idx'),
        ),
        migrations.AddIndex(
            model_name='zonatarifadetalle',
            index=models.Index(fields=['zona', 'estado', 'ciudad'], name='tarifas_zon_zona_id_f4586c_idx'),
        ),
        migrations.AddIndex(
            model_name='zonatarifadetalle',
            index=models.Index(fields=['cp_inicio', 'cp_fin'], name='tarifas_zon_cp_inic_80c4a7_idx'),
        ),
    ]
